wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1650492522
    t:
      1:
      - 2
      - 3
      - 12
      - 45
      - 55
      2:
      - 2
      - 3
      - 12
      - 45
      - 55
      3:
      - 2
      - 16
      4: 3.7.13
      5: 0.12.14
      8:
      - 1
      - 5
dataset_seed:
  desc: null
  value:
  - 0
  - 0
dynamics_noise_cov:
  desc: null
  value: 0.1
elbo_num_samples:
  desc: null
  value: 1
emission_noise_cov:
  desc: null
  value: 0.1
emissions_dim:
  desc: null
  value: 5
inference_seed:
  desc: null
  value:
  - 0
  - 32
latent_dim:
  desc: null
  value: 3
learning_rate:
  desc: null
  value: 0.1
method:
  desc: null
  value: diag-SVAE-rec-only
network_params:
  desc: null
  value:
    out_mean_features: []
    out_var_features: []
num_timesteps:
  desc: null
  value: 200
num_trials:
  desc: null
  value: 10
